### ISSUE TITLE
Agenda and minutes for meetings

### ISSUE THREAD

**Issue by lwjohnst86** [NetCoupler/NetCoupler#16]
This issue is just to list agenda items and some minutes for each meeting. So each comment will be a meeting agenda and associated minutes.

**Comment by lwjohnst86** [comment]
These items can be edited in this comment (use the edit button on the top right)

-----

### August 24th meeting

#### Action items:

For @ClemensWittenbecher:

- Think about what functions end user will use
- ... or what input and output looks like
- Work on #6 mostly. This is a key first step.

For @lwjohnst86:

- Setup infrastructure for unit tests

#### Discussion items:

- Deal with #6

**Comment by ClemensWittenbecher** [comment]
# Next Meeting
__Action items__
For @ClemensWittenbecher
- [x] Draft a roadmap
  - [x] Propose milestones
  - [x] Propose timeline
  - [x] Propose responsibilities and tasks for contributers
- [x] Work on #18 List of functions
  - [x] Structure into main_functions, helper_functions, getter_functions
- [x] Simulate data to test the main_functions (and associated helpers and getters)
  - [x] Define properties and format of the simulated datasets
  - [x] Identify possible functions, packages that can be used to generate the datasets

**Comment by lwjohnst86** [comment]
# Thoughts/notes from 2018-12-20 meeting

- case-control design, but also other designs.
- include a progress bar? for runtime?
- include a limit (as an option?) for the number of nodes/variables to create a network on.
- do a unit test for make network function
- lintr into travis?

**Comment by lwjohnst86** [comment]
closing for now.

**Comment by lwjohnst86** [comment]
# 2021-02-18

## Notes

- compare implementation of below (Clemens version) vs the current (my) version
    - From Clemens: I have checked in the ceramides project– the criteria for direct effect identification were i) P < 0.05 in the non-neighbor-adjusted model (rule1), ii) P < 0.1 in all neighbor-adjusted models (rule 2), iii) same sign of the beta in all the models (rule 3). I did not correct for multiple testing in the primary selection process.
    It would be interesting to apply the current NetCoupler-version to the Ceramides project with these same selection cutoffs and reproduce the results. In principle, it would be good to make these cutoffs' manual setting amendable as an option.

- As idea: provide argument for options as list.

- **Action item**: Determine journal and decide on whether it is method/theory vs application paper

- Surv can have three arguments
    - Or do it as a pre-processing (Surv or strata in mutate)
 
- things throw off when adjusting for variables with similar names (e.g "cer" when there is a "cer14.0" in the network)
    - based on some pattern selection?

- coxph cluster() within the formula interface? Same with strata (but that could be put in preprocessing)
    - cluster doesn't work.

**Comment by lwjohnst86** [comment]
# 2021-03-08

## Agenda

- Update on previous meeting items
- Discuss about useR conference abstract (Luke *should* write something and send out before this meeting)

**Comment by lwjohnst86** [comment]
# 2022-01-08

## Agenda

- Introductions
- Timelines, todo lists
- Who's interested in doing what
- TBD

## Minutes

**Comment by lwjohnst86** [comment]
# 2022-02-14: Co-working

(co-working in Discord)

**Tasks**:

- [ ] Add brainstorming thoughts to https://github.com/NetCoupler/NetCoupler/issues/173 for methods paper (Daniel W. and I.)
- [ ] Go through website and identify areas of improvement for reading and learning how to use NetCoupler
- [ ] Make a better real-world simulated dataset (or give ideas for it)

**Comment by lwjohnst86** [comment]
# 2022-02-23

## Agenda

- Updates on activities

## Minutes

**Comment by lwjohnst86** [comment]
# 2022-03-31

## Agenda

- Update on activities.

## Minutes

- [ ] Decide by next week on journal for application paper, and the requirement for state and maturity of package. (discuss here: https://github.com/NetCoupler/NetCoupler/issues/163)
- Luke will finish last issue than submit to CRAN.
- During next meeting, we plan how to do the writing.

**Comment by lwjohnst86** [comment]
# 2022-04-29

## Agenda

- Update on previous items
- Discuss writing plan

## Minutes
