### ISSUE TITLE
Tasks to complete for final package setup

### ISSUE THREAD

**Issue by lwjohnst86** [NetCoupler/NetCoupler#8]
## Important and necessary tasks 

- [x] Review Pull Requests and merge in
- [x] Review remaining functions with Helena, remove old ones
    - [x] Helena get GitHub account (@helenazacharias)
- [x] Decide on "tidy"/"standard" input/output for functions (#7)
- [x] Create a toy and test dataset (#6)
- [x] Create unit tests of all functions
- [ ] Write up "getting started"/"introduction" documentation in Rmd vignette
- [x] Change function documentation into roxygen2 docs
- [x] Create roxygen2 examples of code usage
- [x] Set up travis and code coverage
- [x] General refactoring of the code (streamline, simplify, etc) (#9)
- [x] Decide on primary functions for v0.1.0 release

## Important/useful but not necessary tasks

- [x] Set up pkgdown website
- [x] Set up appveyor (for Windows builds)

**Comment by lwjohnst86** [comment]
This is to keep track of steps/tasks to do

**Comment by lwjohnst86** [comment]
Revised this a bit to reflect only getting into package format. I'll make another issue specifically for uploading an initial version to CRAN.
